version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: smartfin-postgres
    ports:
      - "5432:5432" # Lewo: Twój komputer (Host), Prawo: Wnętrze kontenera
    environment:
      POSTGRES_USER: finuser
      POSTGRES_PASSWORD: finpass
      POSTGRES_DB: smartfin_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Opcjonalnie: dane przetrwają restart kontenera
        # NOWOŚĆ: Montujemy skrypt SQL do folderu startowego Postgresa
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql