-- 1. Tabela informacji o rewizji (systemowa dla Enversa)
CREATE TABLE revinfo (
rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
revtstmp BIGINT
);

-- 2. Tabela historyczna (Audit Table)
-- Musi zawierać kolumny z oryginalnej tabeli + pola Enversa (rev, revtype)
CREATE TABLE transactions_aud (
db_id BIGINT NOT NULL,
rev INTEGER NOT NULL,
revtype SMALLINT, -- ZAMIAST TINYINT (0: ADD, 1: MOD, 2: DEL)

original_id VARCHAR(255),
date DATE,
amount NUMERIC(19, 2),
currency VARCHAR(10),
amountpln NUMERIC(19, 2),
category VARCHAR(255),
description VARCHAR(255),
category_id BIGINT,

    -- Uwaga: Pól technicznych audytu (created_date itp.) zazwyczaj się nie wersjonuje,
    -- bo one same w sobie są informacją o czasie. Zostawiamy jak wyżej.

PRIMARY KEY (db_id, rev),
CONSTRAINT fk_transactions_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev)
);