-- V12: Naprawia sekwencję revinfo wymaganą przez Hibernate Envers
--
-- Problem: V10 utworzyło kolumnę rev jako GENERATED BY DEFAULT AS IDENTITY
-- (PostgreSQL wewnętrzna sekwencja), ale Hibernate Envers 6.x
-- wywołuje nextval('revinfo_seq') — szuka sekwencji o tej nazwie.
-- Rozwiązanie: Zamiana IDENTITY na jawną sekwencję revinfo_seq.

-- 1. Usunięcie IDENTITY z kolumny rev
ALTER TABLE revinfo ALTER COLUMN rev DROP IDENTITY IF EXISTS;

-- 2. Tworzenie sekwencji revinfo_seq
--    INCREMENT BY 50 = domyślny allocationSize Hibernate Envers (blokowe pobieranie ID)
CREATE SEQUENCE IF NOT EXISTS revinfo_seq
    INCREMENT BY 50
    START WITH 1
    MINVALUE 1;

-- 3. Ustawienie DEFAULT na nextval(revinfo_seq) dla kolumny rev
ALTER TABLE revinfo ALTER COLUMN rev SET DEFAULT nextval('revinfo_seq');

-- 4. Ownership: sekwencja jest "własnością" kolumny revinfo.rev
ALTER SEQUENCE revinfo_seq OWNED BY revinfo.rev;

