-- Tworzy tabelę counters używaną przez encję Counter
-- Składnia zgodna z PostgreSQL
CREATE TABLE counters (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL UNIQUE,
                          counter_value INTEGER
);