-- Tworzymy tabelę użytkowników
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL, -- Tu będzie hash BCrypt
                       role VARCHAR(20) NOT NULL
);

-- Wstawiamy startowego administratora: admin
-- Hasło to: admin123 (poniżej jest jego hash BCrypt)
INSERT INTO users (username, password, role)
VALUES ('admin', '$2a$10$8.UnVuG9HHgffUDAlk8q6OuVGkqNi6pMvL4uC3G22YlY29M7xKxDC', 'ROLE_ADMIN');

-- Wstawiamy zwykłego użytkownika: user
-- Hasło to: user123
INSERT INTO users (username, password, role)
VALUES ('user', '$2a$10$fN5TOWzL5oWpXf.6Pq.L.ORnF.eEunvV3K7Y9hF3v1m/G1p5p9n7G', 'ROLE_USER');