CREATE TABLE categories (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE,
monthly_limit DECIMAL(19, 2) NOT NULL
);

-- Wstawiamy przykładowe limity
INSERT INTO categories (name, monthly_limit) VALUES ('Jedzenie', 1500.00);
INSERT INTO categories (name, monthly_limit) VALUES ('Paginacja', 500.00);
INSERT INTO categories (name, monthly_limit) VALUES ('Praca', 3000.00);
INSERT INTO categories (name, monthly_limit) VALUES ('Wycieczka', 3500.00);
INSERT INTO categories (name, monthly_limit) VALUES ('Zakupy', 4000.00);

-- Modyfikujemy tabelę transakcji, aby wskazywała na ID kategorii zamiast String
ALTER TABLE transactions ADD COLUMN category_id BIGINT;
ALTER TABLE transactions ADD CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id);

-- Opcjonalnie: Przypisujemy istniejące transakcje do kategorii 'Jedzenie' (aby nie psuć danych)
UPDATE transactions SET category_id = (SELECT id FROM categories WHERE name = 'Jedzenie') WHERE category = 'Jedzenie';
UPDATE transactions SET category_id = (SELECT id FROM categories WHERE name = 'Paginacja') WHERE category = 'Paginacja';
UPDATE transactions SET category_id = (SELECT id FROM categories WHERE name = 'Praca') WHERE category = 'Praca';
UPDATE transactions SET category_id = (SELECT id FROM categories WHERE name = 'Wycieczka') WHERE category = 'Wycieczka';
UPDATE transactions SET category_id = (SELECT id FROM categories WHERE name = 'Zakupy') WHERE category = 'Zakupy';